import Navbar from '@/components/navbar';
import type { Metadata } from 'next';

import Link from 'next/link';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <header className="bg-blue-600 text-white p-4">
                    <nav className="container mx-auto flex justify-between">
                        <h1 className="text-xl font-bold">My Next.js Blog</h1>
                        <div className="space-x-4">
                            <Link href="/" className="hover:underline">
                                Home
                            </Link>
                            <Link href="/blog" className="hover:underline">
                                Blog
                            </Link>
                            <Link href="/about" className="hover:underline">
                                About
                            </Link>
                        </div>
                    </nav>
                </header>
                <main className="p-6">{children}</main>
            </body>
        </html>
    );
}
